flowey: copy junit xml instead of rename (#4363)
I was occasionally seeing this error when running windows tests from
wsl, so just copy the file like the comment says instead of moving it
(across filesystem boundaries).

```
Error: failed to rename file from <vmm_tests_dir_on_windows>/target/nextest/ci/junit.xml to <openvmm_repo_dir_in_wsl>/flowey-out/.work/flowey_lib_common__run_cargo_nextest_run_0/junit.xml: Invalid cross-device link (os error 18)
```